### ISSUE TITLE
Managing system dependencies

### ISSUE THREAD

**Issue by patrick-nicodemus** [seereason/Diff#12]
Hi,
My build failed with `/usr/bin/ld.gold: error: cannot find -lgmp`.
I was missing the GMP library dependency, which I resolved on Ubuntu 24 with `sudo apt-get install libgmp3-dev`

I think that the Readme or project description should include this dependency.
I don't know if there's a way to express system dependencies using Cabal, or interact with the system package manager to install packages automatically, or prompt the user to install the library if it's not found, but any of those would be good.

**Comment by Bodigrim** [comment]
This is not specific to `Diff` package, you are unlikely to be able to use the default GHC bindist without `libgmp3-dev`. This is listed as a system requirement of GHC: https://www.haskell.org/ghcup/install/#system-requirements

**Comment by ddssff** [comment]
Should I close this?

**Comment by patrick-nicodemus** [comment]
Yeah, thank you. I thought I had installed GHCup successfully and the error came up when compiling Diff in particular, my apologies.
