### ISSUE TITLE
What are the breaking changes in 1.0

### ISSUE THREAD

**Issue by phadej** [seereason/Diff#13]
Reading the changelog I cannot figure out.

In fact, the changelog for version 1.0 https://hackage.haskell.org/package/Diff-1.0/changelog has only entries for 0.5

**Comment by ddssff** [comment]
Changelog entry pushed

**Comment by ddssff** [comment]
Let me know if you have any comments about the API changes.

**Comment by andreasabel** [comment]
I didn't have any issues with the API changes, worked fine for me.

**Comment by ddssff** [comment]
Ok, closing this.  Good to see some interest in this package.

**Comment by phadej** [comment]
@ddssff you have `ShellCheck` as a reverse-dependency.  Probably most used program written in Haskell after Pandoc. Don't downplay the importance of `Diff`.

**Comment by ddssff** [comment]
Hmm, updating Diff seems to have triggered a build of pandoc as well.

**Comment by andreasabel** [comment]
> Hmm, updating Diff seems to have triggered a build of pandoc as well.

See:
- https://github.com/commercialhaskell/stackage/issues/7559
