### ISSUE TITLE
Export DiffContext

### ISSUE THREAD

**Issue by phadej** [seereason/Diff#14]
In https://hackage.haskell.org/package/Diff-1.0/docs/Data-Algorithm-DiffContext.html

The type `DiffContext` is not exported (not even the opaque name of it), so downstream cannot write type-signatures with `DiffContext`. That is quite annoying.

**Comment by ddssff** [comment]
Should I just eliminate the explicit export list?   I don't think there's any dangerous magic in there.

**Comment by ddssff** [comment]
Did you mean the types `ContextDiff` and `Hunk`?

**Comment by phadej** [comment]
> Should I just eliminate the explicit export list?

IMHO keeping the API as small as possible has benefits: if non-exported  things are changed, its not a breaking change.

And in particular, I'd suggest to *always* use export lists. That way a small helper function won't accidentally become a part of public API.

**Comment by ddssff** [comment]
`ContextDiff` and `Hunk` are now exported in versions >= 1.0.1.
