### ISSUE TITLE
Please tag releases on this repo so I can diff the versions

### ISSUE THREAD

**Issue by andreasabel** [seereason/Diff#15]
Please tag releases on this repo so I can Diff the versions (terrible pun, I know, nevertheless intended, I pay you a beer for compensation if we ever meet in person).

Seriously, having tags would be terribly useful to find out what changed, especially in the light of a _missing changelog for a major-major version bump_.  (This is only in italics, but envision it in UPPER CASE AT MAXIMUM VOLUME.)
- #13

**Comment by ddssff** [comment]
Ok ok :-)   Tuesday I will do this.

**Comment by ddssff** [comment]
Went back to 0.3.4, any interest in ancient history?

**Comment by andreasabel** [comment]
Thanks!
Recent history is enough...
