### ISSUE TITLE
Add Bifunctor instance for PolyDiff

### ISSUE THREAD

**Issue by jonathanlking** [seereason/Diff#2]
The following `Bifunctor` instance would be very handy:

```haskell
instance Bifunctor PolyDiff where
  bimap f _ (First a) = First (f a)
  bimap _ g (Second b) = Second (g b)
  bimap f g (Both a b) = Both (f a) (g b)
```

I appreciate supporting `base >= 3 && <= 6` makes things slightly more complicated, as `Bifunctor` is only available since `base-4.8.0.0`. The two options I can think of are using a `CPP` macro, or increasing the minimum bounds of `base`.

I'm happy to open a PR with either approach (or something else!).

**Comment by ddssff** [comment]
I think we can abandon base older than 4.8.0.0.  If someone complains I'll welcome a PR with ifdefs.

**Comment by ddssff** [comment]
Have you noticed any slowness in the diff function?  I may have seen this when running in the browser via ghcjs.

**Comment by jonathanlking** [comment]
> Have you noticed any slowness in the diff function? I may have seen this when running in the browser via ghcjs.

We're only using the `getGroupedDiff` function (on GHC 8.8.4 targeting x86) and it's only used as part of tests.
I haven't noticed it being particularly slow, but that said these tests are not something that we've profiled, as they're fast enough.

**Comment by ddssff** [comment]
I can do the CPP.

**Comment by Bodigrim** [comment]
@ddssff did you test it with GHC 9.6? I suspect `instance Functor` is missing.

**Comment by ddssff** [comment]
I don't have access to ghc-9.6.  Stuck on 8.10.

**Comment by Bodigrim** [comment]
Sorry, I’m AFK until the next week. If you wish, once back home, I can generate a GitHub Actions CI setup with [`haskell-ci`](https://hackage.haskell.org/package/haskell-ci ) covering a range of GHCs up to 9.6.

**Comment by Bodigrim** [comment]
@ddssff could you possibly make a release some time soon?

**Comment by ddssff** [comment]
Hackage upload?  Will do.

**Comment by Bodigrim** [comment]
Yes, please.

**Comment by ddssff** [comment]
Does O(ND) in the title refer to time or space complexity?

**Comment by Bodigrim** [comment]
Time is O(ND) and space is O(D^2). 

I'm not sure "O(ND)" is terribly helpful as a top-level package description without explaining what D refers to. It might be helpful to bring Cabal "description:" field in line with the module header:

https://github.com/seereason/Diff/blob/026aef240788c976380aa00635aa0ff287fffff7/Diff.cabal#L3-L4

https://github.com/seereason/Diff/blob/026aef240788c976380aa00635aa0ff287fffff7/src/Data/Algorithm/Diff.hs#L10-L14

**Comment by ddssff** [comment]
How about this:
```
synopsis:            Diff algorithm in pure Haskell
description:         Implementation of the standard diff algorithm, and utilities for pretty printing.  Time complexity is proportional to N (input length) & D (number of differences).  Space complexity is D^2.
```

**Comment by Bodigrim** [comment]
Thanks for a quick turnaround with a release, really much appreciated.

> How about this:

Looks great! And today I learned that one can edit package description via revision :)

**Comment by ddssff** [comment]
I'm thinking of removing 'getContextDiffOld' - I can't see how it could be
useful to anyone.

**Comment by Bodigrim** [comment]
> I'm thinking of removing 'getContextDiffOld' - I can't see how it could be useful to anyone.

Makes sense to me.

**Comment by ddssff** [comment]
I judge all this stuff done.
