### ISSUE TITLE
Fix space complexity in the docs

### ISSUE THREAD

**Issue by Bodigrim** [seereason/Diff#3]
https://github.com/seereason/Diff/blob/d106e4d52135c05aa492509d428a3a12a13d2154/src/Data/Algorithm/Diff.hs#L10-L13

The space complexity used to be O(mn) in `Diff-0.1.*`, but since `Diff-0.2` is at most O(max(m,n)). 

Upd.: Actually, maybe my mental model of snakes is wrong? I imagine that they share initial segments, but even if they don't at all, the absolutely worst case is O(n d), where d is a number of differences, which is still much better than O(m n).

**Comment by ddssff** [comment]
I wonder if there might be something wrong with the implementation, it can be extraordinary slow.

**Comment by Bodigrim** [comment]
I read the original Myers' paper today. Let inputs be of size O(N), and D be the number of differences between them.

* Good news: space complexity in the documentation is over-pessimistic. An algorithm with O(N D) time complexity cannot possibly have O(N^2) space complexity - it simply lacks time to allocate that much. We can safely update documentation claiming O(N D) as both time and space complexity. 

* Bad news: the space complexity O(N D) is a precise estimate. We maintain up to D snakes, each of which by the end of the algorithm can grow up to N elements in the list. That's because we store not only vertical or horizontal segments (`F`irst and `S`econd in terms of `Diff`), but also diagonal ones (`B`oth). 

* It should be feasible to fix this: it's sufficient to store only vertical or horizontal segments and restore diagonals from the input data greedily. This would bring down the space complexity to O(D^2), which is much more practical and matches the complexity of the first algorithm in the paper. 

Ideally one should strive to implement the divide-and-conquer algorithm with O(N) space complexity from the second part of the paper, but that's much more work.

**Comment by ddssff** [comment]
Thanks for looking into this!
